she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # /news/
    path('<int:pk>/', views.StoryView.as_view(), name='story'), 
    path('add-story/', views.AddStoryView.as_view(), name='newStory') # /news/add-story
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')), # /news/
    path('admin/', admin.site.urls), # /admin/
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')), #/users/login users/logout
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
# from .views import ProfileView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'
urlpatterns = [
	path('create-account/', CreateAccountView.as_view(), name='createAccount'),
	# path('<int:pk>/', ProfileView.as_view(), name='profile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE #deletes stories whenn author is deleted
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    img_url = models.URLField(max_length = 250, default="https://picsum.photos/600")

    class Meta:
        ordering = ['pub_date'] #ordering by date

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import TextInput
from .models import NewsStory

# allow Django to infer all the form fields and validation from a model
class StoryForm(ModelForm):
    # nested class we want Django to infer from
    class Meta:
        model = NewsStory
        # list of fields to be included in the form
        fields = ['title', 'content','pub_date', 'img_url']
        widgets = {
            'title': TextInput(attrs={
                'style': 'min-width: 50%;', 
            }),
            'content': TextInput(attrs={
                'style': 'min-width: 80%;' 'min-height:200px;'
            }),
        	'pub_date': forms.DateInput(format=('%m/%d/%Y'),attrs = {
                'class':'form-control',
                'placeholder':'Select a date',
                'type':'date'}),
            'img_url': TextInput(attrs={
                'style': 'min-width: 50%;', 
            }),           
    	}

# django form fields are customised via widget attributes

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
    
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    # use the name we called the path in urlpatterns to get the url path
    success_url = reverse_lazy('news:index')

    # overriding form_valid which is on generic.CreateView
    def form_valid(self, form):
        #set author to user logged in
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

# Create your views here.
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

she_codes_news/news/templates/news/createStory.html
{% extends 'base.html' %}

{% block content %}
<h2>Create New Story </h2>

<div class="createStory">
    <form action="" method="post">
    {% comment %} security mechanism to prevent cheeky people trying rebuild your server (cross-site request forgery) {% endcomment %}
        {% csrf_token %}
        {{form.as_p}}
        <input type="Submit" value="Submit">
    </form>
</div>
{% endblock content %}

she_codes_news/news/templates/news/index.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock  %}
    {% block content %}
    
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock  %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src={{ story.img_url }}>
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            <img src="../static/news/images/{{ story.img_url }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Queenie">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock  %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock  %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="#">Logged in as <b>{{user.username}}</b></a>
        <a href="{% url 'news:newStory' %}">Write New Story</a>
        <button type="submit" onclick="location.href='{% url "logout" %}'">Logout</button>
    {% else %}
        <a href="{% url 'users:createAccount' %}">Sign Up</a>
        <button type="submit" onclick="location.href='{% url "login" %}'">Login</button>
    {% endif %}
  
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>

{% endblock content %}